# for sourceType: 'module'
#  look at documentation ESLint in 'Specifying Environments':
#  - es6 - enable all ECMAScript 6 features except for modules
#    (this automatically sets the ecmaVersion parser option to 6).
parserOptions:
  sourceType: 'module'

env:
  es6: true
  browser: true
  commonjs: true
  mocha: true

extends: 'htmlacademy/es6'
